# Generated by Django 3.0.2 on 2020-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slamer', '0002_auto_20200328_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged',
            field=models.BooleanField(null=True),
        ),
    ]
