# Generated by Django 3.0.2 on 2020-03-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slamer', '0004_auto_20200329_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
